version: '2.1'
orbs:
  node: circleci/node@x.y
jobs:
  build_and_deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: sudo npm install -g surge
      - run: surge build
workflows:
  deploy:
    jobs:
      - build_and_deploy
