version: '2.1'
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
          override-ci-command: npm install --legacy-peer-deps
      - run: npm run build
      #- run: sudo npm install -g surge
      - run: npm run deploy
workflows:
  deploy:
    jobs:
      - build_and_deploy
